# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# REVIEW: The Ubuntu and macOS builds seem to be finding a prebuild in build/Release/node-leveldb.node and as a result not building and using that instead.

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Run on new tags

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 16.x
            wasm: false
          - os: windows-latest
            node-version: 16.x
            wasm: false
          - os: macos-latest
            node-version: 16.x
            wasm: false
          - os: windows-latest
            node-version: 16.x
            wasm: true
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      env:
        BUILDING_WASM: ${{ matrix.wasm }}
        DEBUG: leveldb
    - run: npm run build --if-present
      env:
        BUILDING_WASM: ${{ matrix.wasm }}
        DEBUG: leveldb
    - run: npm test
      # TEMP: This is until it is decided whether or not there should be a test for WASM, since the build environment could vary.
      if: matrix.wasm == false
      env:
        BUILDING_WASM: ${{ matrix.wasm }}
        DEBUG: leveldb
      # DEBUG
    - name: DEBUG - List Files (WASM) (Windows)
      if: matrix.wasm == true && matrix.os == 'windows-latest' && always()
      shell: pwsh
      run: Get-ChildItem -Recurse -Force | Select-Object FullName
    - run: npm run postci
      env:
        BUILDING_WASM: ${{ matrix.wasm }}
        DEBUG: leveldb
      id: postci
    # - name: Display structure of downloaded files
    #   run: ls -R
    - name: Upload artifact (Node)
      if: matrix.wasm == false
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ steps.postci.outputs.PLATFORM_STRING }}
        path: |
          build/Release/*
    - name: Upload artifact (WASM (JS))
      if: matrix.wasm == true
      uses: actions/upload-artifact@v4
      with:
        name: dist-leveldb_wasm.js
        path: |
          build-wasm/leveldb_wasm.js
    - name: Upload artifact (WASM)
      if: matrix.wasm == true
      uses: actions/upload-artifact@v4
      with:
        name: dist-leveldb_wasm.wasm
        path: |
          build-wasm/leveldb_wasm.wasm
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0

  release:
    permissions:
      contents: write
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: helpers

      - run: npm install
        env: 
          SKIP_BUILD: true

      # - name: Publish to npm
      #   run: npm publish --provenance

      - id: version # extract version from package.json file, to replace the output from `publish`
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.version.outputs.version }}" \
            --title "Release ${{ steps.version.outputs.version }}" \
            --notes "${{ steps.version.outputs.version }}"

      - name: Display structure of downloaded files
        run: ls -R
